# Generated by Django 6.0.6 on 2026-07-07 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('parsed_text', models.TextField(blank=True)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('improvement_suggestions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='JobMatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skill_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_match_scores', to='resumes.resume')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('resume', 'job'), name='unique_match_per_resume_job')],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(choices=[('PROFILE', 'Profile Based'), ('RESUME', 'Resume Based'), ('SWIPE_BEHAVIOR', 'Swipe Behavior'), ('HYBRID', 'Hybrid')], default='HYBRID', max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='jobs.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='profiles.jobseekerprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job_seeker', 'job'), name='unique_recommendation_per_job_seeker_job')],
            },
        ),
    ]
