# Generated by Django 6.0.6 on 2026-08-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parsed_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
